//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RimWorldModBrowser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RimWorldModBrowser.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By {0}.
        /// </summary>
        public static string AuthorBy {
            get {
                return ResourceManager.GetString("AuthorBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelCaption {
            get {
                return ResourceManager.GetString("CancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mods found, check your settings.
        /// </summary>
        public static string CheckSettings {
            get {
                return ResourceManager.GetString("CheckSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dnSpy Path:.
        /// </summary>
        public static string dnSpyPath {
            get {
                return ResourceManager.GetString("dnSpyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dnSpy path specified does not exist.
        /// </summary>
        public static string dnSpyPathBadError {
            get {
                return ResourceManager.GetString("dnSpyPathBadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DoneCaption {
            get {
                return ResourceManager.GetString("DoneCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Description:.
        /// </summary>
        public static string ModDescription {
            get {
                return ResourceManager.GetString("ModDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RimWorld Mods Directory specified does not exist.
        /// </summary>
        public static string RWModsDirBadError {
            get {
                return ResourceManager.GetString("RWModsDirBadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RimWorld Local Mods Directory (RimWorld\Mods):.
        /// </summary>
        public static string RWModsDirectoryCaption {
            get {
                return ResourceManager.GetString("RWModsDirectoryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RimWorld Mods Directory specified appears to be incorrect.
        /// </summary>
        public static string RWModsDirIncorrectError {
            get {
                return ResourceManager.GetString("RWModsDirIncorrectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RimWorld Workshop Directory specified does not exist.
        /// </summary>
        public static string RWWorkshopBadError {
            get {
                return ResourceManager.GetString("RWWorkshopBadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RimWorld Workshop Directory (Game ID: 294100):.
        /// </summary>
        public static string RWWorkshopCaption {
            get {
                return ResourceManager.GetString("RWWorkshopCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RimWorld Workshop Directory specified appears to be incorrect.
        /// </summary>
        public static string RWWorkshopDirIncorrectError {
            get {
                return ResourceManager.GetString("RWWorkshopDirIncorrectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchGhostText {
            get {
                return ResourceManager.GetString("SearchGhostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a mod to get started.
        /// </summary>
        public static string SelectAMod {
            get {
                return ResourceManager.GetString("SelectAMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} out of {1} mods.
        /// </summary>
        public static string StatusBarLoadCount {
            get {
                return ResourceManager.GetString("StatusBarLoadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} out of {1} mod.
        /// </summary>
        public static string StatusBarLoadCountSingular {
            get {
                return ResourceManager.GetString("StatusBarLoadCountSingular", resourceCulture);
            }
        }
    }
}
